'use client'
import { Providers } from './providers'
import './globals.css'
import { Inter } from 'next/font/google'

// export const metadata = {
//   title: 'Connect',
//   description: 'Generated by create next app',
// }
const inter = Inter({ subsets: ['latin'] })
type Props = {
  children: React.ReactNode
}

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-full h-full flex flex-col justify-center items-center  text-foreground bg-black ">
          <Providers>{children}</Providers>
        </main>
      </body>
    </html>
  )
}
// bg-background bg-#f4f2ee
