// import styles from './website.module.css'
import ModalManager from '@/components/Modal/modalManager'
import Navbar from '@/components/Navbar'
import { getServerSession } from 'next-auth'

type Props = {
  children: React.ReactNode
}
export const metadata = {
  title: 'Connect',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }: Props) {
  return (
    <>
      <section>
        <Navbar />
        <main id="main">{children}</main>
      </section>
      <ModalManager />
    </>
  )
}
